"""Oracle Select AI-backed SQL generator."""

from __future__ import annotations

import os
from collections.abc import Callable
from pathlib import Path
from typing import Any

from dotenv import load_dotenv

try:
    import oracledb
except ModuleNotFoundError:  # pragma: no cover - depends on local environment
    oracledb = None  # type: ignore[assignment]


ConnectionFactory = Callable[[], Any]


class OracleSelectAISQLGenerator:
    """Generate SQL by sending the prepared prompt to Oracle Select AI."""

    def __init__(
        self,
        profile_name: str | None = None,
        connection_factory: ConnectionFactory | None = None,
    ) -> None:
        load_dotenv()
        self.profile_name = (
            profile_name if profile_name is not None else os.getenv("SELECT_AI_PROFILE")
        )
        self.connection_factory = connection_factory or self._connect_adb

    def generate(self, prompt: str) -> dict:
        """Return SQL generated by Select AI, or an explanatory skipped/error payload."""
        prompt = prompt.strip()
        if not prompt:
            return self._result(
                sql=None,
                reasoning="SQL generation skipped because the prompt was empty.",
            )

        if not self.profile_name:
            return self._result(
                sql=None,
                reasoning="SQL generation skipped because SELECT_AI_PROFILE is not set.",
            )

        try:
            with self.connection_factory() as connection:
                generated_sql = self._call_select_ai(connection, prompt)
        except Exception as exc:  # pragma: no cover - exercised by live DB smoke tests
            return self._result(
                sql=None,
                reasoning="Oracle Select AI SQL generation failed.",
                error=str(exc),
            )

        return self._result(
            sql=generated_sql,
            reasoning=(
                "Generated with Oracle Select AI using DBMS_CLOUD_AI.GENERATE "
                "action showsql."
            ),
        )

    def _call_select_ai(self, connection: Any, prompt: str) -> str:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT DBMS_CLOUD_AI.GENERATE(
                    prompt       => :prompt,
                    profile_name => :profile_name,
                    action       => 'showsql'
                )
                FROM dual
                """,
                {
                    "prompt": prompt,
                    "profile_name": self.profile_name,
                },
            )
            row = cursor.fetchone()

        if not row or row[0] is None:
            raise RuntimeError("Oracle Select AI returned no SQL.")

        return self._read_db_value(row[0]).strip()

    def _connect_adb(self) -> Any:
        if oracledb is None:
            raise RuntimeError("The oracledb package is not installed.")

        connect_kwargs: dict[str, str] = {
            "user": self._required_env("ADB_USER"),
            "password": self._required_env("ADB_PASSWORD"),
            "dsn": self._required_env("ADB_DSN"),
        }

        wallet_location = os.getenv("ADB_WALLET_LOCATION")
        if wallet_location:
            resolved_wallet_location = self._resolve_project_path(wallet_location)
            connect_kwargs["config_dir"] = resolved_wallet_location
            connect_kwargs["wallet_location"] = resolved_wallet_location

        wallet_password = os.getenv("ADB_WALLET_PASSWORD")
        if wallet_password:
            connect_kwargs["wallet_password"] = wallet_password

        return oracledb.connect(**connect_kwargs)

    def _required_env(self, name: str) -> str:
        value = os.getenv(name)
        if not value:
            raise RuntimeError(f"Missing required environment variable: {name}")
        return value

    def _resolve_project_path(self, value: str) -> str:
        path = Path(value).expanduser()
        if not path.is_absolute():
            path = Path.cwd() / path
        return str(path.resolve())

    def _read_db_value(self, value: Any) -> str:
        if hasattr(value, "read"):
            return str(value.read())
        return str(value)

    def _result(
        self,
        sql: str | None,
        reasoning: str,
        error: str | None = None,
    ) -> dict:
        return {
            "sql": sql,
            "clarification_question": None,
            "reasoning": reasoning,
            "provider": "oracle_select_ai",
            "error": error,
        }


def generate_sql(prompt: str) -> str:
    """Compatibility wrapper that returns only the generated SQL text."""
    result = OracleSelectAISQLGenerator().generate(prompt)
    return result["sql"] or ""
