"""Oracle Select AI-backed SQL generator."""

from __future__ import annotations

import os
from collections.abc import Callable
from typing import Any

from dotenv import load_dotenv

from app.sql.fallbacks import fallback_sql_for_prompt
from app.sql.oracle_connection import connect_adb

ConnectionFactory = Callable[[], Any]


class OracleSelectAISQLGenerator:
    """Generate SQL by sending the prepared prompt to Oracle Select AI."""

    def __init__(
        self,
        profile_name: str | None = None,
        connection_factory: ConnectionFactory | None = None,
    ) -> None:
        load_dotenv()
        self.profile_name = (
            profile_name if profile_name is not None else os.getenv("SELECT_AI_PROFILE")
        )
        self.connection_factory = connection_factory or connect_adb

    def generate(self, prompt: str) -> dict:
        """Return SQL generated by Select AI, or an explanatory skipped/error payload."""
        prompt = prompt.strip()
        if not prompt:
            return self._result(
                sql=None,
                reasoning="SQL generation skipped because the prompt was empty.",
            )

        fallback_sql = fallback_sql_for_prompt(prompt)
        if not self.profile_name:
            if fallback_sql:
                return self._result(
                    sql=fallback_sql,
                    reasoning=(
                        "SELECT_AI_PROFILE is not set; used deterministic fallback SQL."
                    ),
                    provider="local_fallback",
                )
            return self._result(
                sql=None,
                reasoning="SQL generation skipped because SELECT_AI_PROFILE is not set.",
            )

        try:
            with self.connection_factory() as connection:
                generated_sql = self._call_select_ai(connection, prompt)
        except Exception as exc:  # pragma: no cover - exercised by live DB smoke tests
            if fallback_sql:
                return self._result(
                    sql=fallback_sql,
                    reasoning="Oracle Select AI failed; used deterministic fallback SQL.",
                    provider="local_fallback",
                    error=str(exc),
                )
            return self._result(
                sql=None,
                reasoning="Oracle Select AI SQL generation failed.",
                error=str(exc),
            )

        return self._result(
            sql=generated_sql,
            reasoning=(
                "Generated with Oracle Select AI using DBMS_CLOUD_AI.GENERATE "
                "action showsql."
            ),
        )

    def _call_select_ai(self, connection: Any, prompt: str) -> str:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT DBMS_CLOUD_AI.GENERATE(
                    prompt       => :prompt,
                    profile_name => :profile_name,
                    action       => 'showsql'
                )
                FROM dual
                """,
                {
                    "prompt": prompt,
                    "profile_name": self.profile_name,
                },
            )
            row = cursor.fetchone()

        if not row or row[0] is None:
            raise RuntimeError("Oracle Select AI returned no SQL.")

        return self._read_db_value(row[0]).strip()

    def _read_db_value(self, value: Any) -> str:
        if hasattr(value, "read"):
            return str(value.read())
        return str(value)

    def _result(
        self,
        sql: str | None,
        reasoning: str,
        provider: str = "oracle_select_ai",
        error: str | None = None,
    ) -> dict:
        return {
            "sql": sql,
            "clarification_question": None,
            "reasoning": reasoning,
            "provider": provider,
            "error": error,
        }


def generate_sql(prompt: str) -> str:
    """Compatibility wrapper that returns only the generated SQL text."""
    result = OracleSelectAISQLGenerator().generate(prompt)
    return result["sql"] or ""
